function cdi = CepsaDrillingIndex()

%% This function draws the main screen for the application of Cepsa Drilling Index
clearvars *;
close all;

%% Variable definitions
%vertregions   = 2;             % Number of vertical regions
%horzregions   = 1;             % Maximum number of horizontal regions
% Main form
horzmargin    = 0.01;           % Left margin of GUI
vertmargin    = 0.01;           % Bottom margin of GUI
hzsep         = 0.01;           % Horizontal spacing
vertsep       = 0.01;           % Vertical spacing

%% Controls
% Upper Pannel
upper_pannel_height  = 0.8;                 % Upper pannel height
upper_pannel_width   = 1 - 2 * horzmargin;  % Upper pannel width
upper_pannel_X       = horzmargin;          % X coordinate of the origin of the Upper pannel
upper_pannel_Y       = 1 - vertmargin - ...
    upper_pannel_height;                    % Y coordinate of the origin of the Upper pannel

% Lower part of the upper pannel
lower_upper_pannel_height  = 0.8;                 % Lower Upper pannel height
lower_upper_pannel_width   = 1 - 4 * horzmargin;  % Lower Upper pannel width
lower_upper_pannel_X       = 2 * horzmargin;      % X coordinate of the origin of the Lower Upper pannel
lower_upper_pannel_Y       = 2 * vertsep;         % Y coordinate of the origin of the Lower Upper pannel

% Lower Pannel
lower_pannel_height  = 1 - 2 * vertmargin - ...
    vertsep - upper_pannel_height;
lower_pannel_width   = upper_pannel_width;
lower_pannel_X       = horzmargin;
lower_pannel_Y       = vertmargin;

% Well Type Pannel
well_type_pannel_height = 0.15;
well_type_pannel_width = ( 1 - 4 * horzmargin - 2* hzsep ) / 2;
well_type_pannel_X = upper_pannel_X + hzsep;
well_type_pannel_Y = 1 - vertmargin - vertsep - well_type_pannel_height;

% Well Units Pannel
units_pannel_height = well_type_pannel_height;
units_pannel_width = ( 1 - 4 * horzmargin - 2* hzsep ) / 2;
units_pannel_X = well_type_pannel_X + units_pannel_width + 2* hzsep;
units_pannel_Y = 1 - vertmargin - vertsep - units_pannel_height;

%% Structure of the app
cdi = figure( 'MenuBar', 'none',...
    'Name', 'Cepsa Drilling Index Tools', ...
    'Units', 'normalized',...
    'OuterPosition', [ .2 .025 .6 .95 ], ...
    'Resize', 'off', ...
    'NumberTitle', 'off', ...
    'Color', [ 1 1 1 ] );
% Create the variables structure and store initial data there

cdi.UserData.variables.Offshore = 0;
cdi.UserData.variables.Onshore = 1;
cdi.UserData.variables.LengthUnits = 'm';
cdi.UserData.variables.DensityUnits = 'SG';
cdi.UserData.variables.ReservoirAge_popup = { 'Tertiary or Later', 'Cretaceous', ...
    'Jurassic', 'Triassic', 'Pre-Triassic' };
cdi.UserData.variables.CountryLandList = { 'Yemen', 'Saudia Arabia', ...
    'Egypt', 'Algeria', 'Tunisia', 'Colombia', 'Ecuador', 'Trinidad', ...
    'Indonesia', 'Papua New Guinea', 'Australia', 'New Zealand', 'Oman', ...
    'Qatar', 'Syria', 'Iran', 'Azerbaijan', 'Russia', 'Kazakhstan', ...
    'Sakhalin Island', 'Gabon', 'Angola', 'Mozambique', 'Ethiopia', ...
    'Austria', 'Italy', 'Albania', 'Romania', 'Pakistan', 'India', ...
    'Libya', 'Niger', 'Nigeria', 'Sudan', 'Uganda', 'Netherlands', ...
    'Germany', 'France', 'UK', 'Thailand', 'Bangladesh', 'China', ...
    'Bolivia', 'Brazil', 'Argentina' };
cdi.UserData.variables.CountryOffshoreList = { 'UK', 'Ireland', 'Faroes', ...
    'Nigeria', 'Mauritania', 'Ivory Coast', 'Benin', 'Ghana', 'Guinea-Bissau', ...
    'Malaysia', 'Brunei', 'India', 'Vietnam', 'Myanmar', 'Cambodia', 'Bangladesh', ...
    'Indonesia', 'Phillipines', 'Papua New Guinea', 'Angola', 'South Africa', ...
    'Mozambique', 'Namibia', 'Kenya', 'Norway' , 'Australia', 'New Zealand', 'China', ...
    'Sakhalin Island' , 'Iran', 'Qatar', 'Azerbaijan', 'Bahrain', 'Turkmenistan', 'UAE', ...
    'Pakistan', 'US GOM Deep', 'Egypt', 'Palestine', 'Trinidad', 'Venezuela', 'Colombia', ...
    'Cameroon', 'Gabon', 'Equatorial Guinea', 'Netherlands', 'Congo Brazzaville', ...
    'Congo Kinshasa', 'Brazil', 'Argentina', 'Croatia', 'Libya', 'Italy', 'Tunisia', ...
    'Spain', 'Denmark', 'Canada', 'Greenland' };

% Variables to handle several operations
country_popup = sort( cdi.UserData.variables.CountryLandList );
offshore_maximum_angle_popup = { '<5', '5-24', '25-42', '43-64', '65-84', '85-94', '95-170' };
onshore_maximum_angle_popup = { '<5', '5-24', '25-44', '45-64', '65-84', '85-89', '90-170' };
offshore_bit_size_popup = { '<7', '7-9', '9-12', '>12' };
onshore_bit_size_popup = { '<7', '7-9', '>9' };
offshore_number_of_casings_popup = { 1, 2, 3, 4, 5, '>=6' };
onshore_number_of_casings_popup = { 1, 2, 3, 4, '>5' };
welltype = 'Onshore';
%factor_functions = { countryFactor, WDFactor, DIFactor, maximumAngleFactor, ...
%    HSFactor, FinalBitSizeFactor, NumberofCasingFactor, MaximumMWFactor, ...
%    HPFacor, ReservoirAgeFactor, BatchFactor };
% Internal Variables
cdi.UserData.variables.SurfaceElevation = 0;
cdi.UserData.variables.SpudDepth = 0;
cdi.UserData.variables.MTD = 0;
cdi.UserData.variables.DrilledInterval = 0;
cdi.UserData.variables.HorSection = 0;
cdi.UserData.variables.Angle = 0;
cdi.UserData.variables.BitSize = 0;
cdi.UserData.variables.NumberOfCasings = 0;
cdi.UserData.variables.MudWeight = 0;
cdi.UserData.variables.HPWell = 0;
cdi.UserData.variables.ReservoirAge = cdi.UserData.variables.ReservoirAge_popup{ 1 };
cdi.UserData.variables.Country = country_popup{ 1 };
cdi.UserData.variables.BatchOrCampaign = 0;
% Factors (variables' names generated dynamically )
for i = 1:11
    eval( sprintf( 'cdi.UserData.variables.factor%d = 0', i ) );
end
%% Interface definition
% Upper Pannel
cdi.UserData.upper_pannel = uipanel( 'Parent', cdi, ...
                                     'BackgroundColor', [ 255 255 255 ] / 255, ...
                                     'Units', 'normalized', ...
                                     'Position', [ upper_pannel_X, ...
                                                   upper_pannel_Y, ...
                                                   upper_pannel_width, ...
                                                   upper_pannel_height ] );
                                 
% Lower Pannel
cdi.UserData.lower_pannel = uipanel( 'Parent', cdi, ...
                                     'BackgroundColor', [ 255 255 255 ] / 255, ...
                                     'Units', 'normalized', ...
                                     'Position', [ lower_pannel_X, ...
                                                   lower_pannel_Y, ...
                                                   lower_pannel_width, ... 
                                                   lower_pannel_height ] );
% Well Type Pannel (Button Group)
cdi.UserData.well_type_pannel = uibuttongroup( 'Parent', cdi.UserData.upper_pannel, ...
                                               'Position', [ well_type_pannel_X, ...
                                                             well_type_pannel_Y, ...
                                                             well_type_pannel_width, ...
                                                             well_type_pannel_height ], ...
                                                'Title', 'Well type', ...
                                                'FontWeight', 'bold', ...
                                                'FontSize', 16, ...
                                                'BackgroundColor', [ 255 255 255 ] / 255,...
                                                'SelectionChangedFcn',@welltypeselection );
                                             
cdi.UserData.onshore = uicontrol( 'Parent', cdi.UserData.well_type_pannel, ...
                                  'Style', 'radiobutton',...
                                  'Units', 'normalized', ...
                                  'Position', [ 0.1 0.7 0.8 0.3 ], ...
                                  'BackgroundColor', [ 1 1 1 ], ...
                                  'String', 'Land Well',...
                                  'FontSize', 12, ...
                                  'HandleVisibility','off');
                              
cdi.UserData.offshore = uicontrol( 'Parent', cdi.UserData.well_type_pannel, ...
                                   'Style', 'radiobutton',...
                                   'Units', 'normalized', ...
                                   'Position', [ 0.1 0.2 0.8 0.3 ], ...
                                   'BackgroundColor', [ 1 1 1 ], ...
                                   'String','Offshore Well',...
                                   'FontSize', 12, ...
                                   'HandleVisibility','off');                                                  
                                               
% Units panel Button Group                                               
cdi.UserData.units_pannel = uipanel( 'Parent', cdi.UserData.upper_pannel, ...
                                           'Position', [ units_pannel_X, ...
                                                         units_pannel_Y, ...
                                                         units_pannel_width, ...
                                                         units_pannel_height ], ...
                                            'Title', 'Units', ...
                                            'FontWeight', 'bold', ...,
                                            'FontSize', 16, ...
                                            'BackgroundColor', [ 255 255 255 ] / 255 );

% Dropbown buttons with label 
cdi.UserData.length_tag = uicontrol( 'Parent', cdi.UserData.units_pannel, ...
                                  'Style', 'text',...
                                  'Units', 'normalized', ...
                                  'Position', [ 0.1 0.65 0.2 0.3 ], ...
                                  'BackgroundColor', [ 1 1 1 ], ...
                                  'String','Length',...
                                  'FontSize', 12, ...
                                  'HandleVisibility','off' );
                                                                
cdi.UserData.length = uicontrol( 'Parent', cdi.UserData.units_pannel, ...
                                 'Style', 'popup',...
                                 'Units', 'normalized', ...
                                 'Position', [ 0.5 0.7 0.4 0.3 ], ...
                                 'BackgroundColor', [ 1 1 1 ], ...
                                 'String', { 'm', 'ft' },...
                                 'FontSize', 12, ...
                                 'HandleVisibility','off', ...
                                 'Callback', { @lengthselection } );
                             

cdi.UserData.density_tag = uicontrol( 'Parent', cdi.UserData.units_pannel, ...
                                  'Style', 'text',...
                                  'Units', 'normalized', ...
                                  'Position', [ 0.1 0.15 0.2 0.3 ], ...
                                  'BackgroundColor', [ 1 1 1 ], ...
                                  'String','Density',...
                                  'FontSize', 12, ...
                                  'HandleVisibility','off');

cdi.UserData.density = uicontrol( 'Parent', cdi.UserData.units_pannel, ...
                                   'Style', 'popup',...
                                   'Units', 'normalized', ...
                                   'Position', [ 0.5 0.2 0.4 0.3 ], ...
                                   'BackgroundColor', [ 1 1 1 ], ...
                                   'String',{ 'SG', 'kg/m^3', 'kpam', 'ppg', 'lb/ft^3', 'psif'  },...
                                   'FontSize', 12, ...
                                   'HandleVisibility','off', ...
                                   'Callback', { @densityselection } );

% Lower part of upper pannel
cdi.UserData.lower_upper_pannel = uipanel( 'Parent', cdi.UserData.upper_pannel, ...
                                           'Units', 'normalize', ...
                                           'Position', [ lower_upper_pannel_X, ...
                                                   lower_upper_pannel_Y, ...
                                                   lower_upper_pannel_width, ...
                                                   lower_upper_pannel_height ], ...
                                           'BackgroundColor', [ 1 1 1 ], ...
                                           'Title', 'DataEntry', ...
                                           'FontSize', 16, ...
                                           'FontWeight', 'bold');
                                       
if ( cdi.UserData.variables.Offshore ) 
    surface_elevation_string = 'Water Depth Elevation:';
    spud_depth_string = 'Spud Depth @ Mud line:';
    country_popup = sort( cdi.UserData.variables.CountryOffshoreList );   
else
    surface_elevation_string = 'Rotary Table Height:';
    spud_depth_string = 'Spud Depth @ Cellar Bottom:';
    country_popup = sort( cdi.UserData.variables.CountryLandList );
end

length_units = cdi.UserData.variables.LengthUnits; 
density_units = cdi.UserData.variables.DensityUnits;

%% Data entry labels and input controls
% Country
cdi.UserData.country_selection = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                            'Style', 'text', ...
                                            'String', 'Country:', ...
                                            'HorizontalAlignment', 'left', ...
                                            'Units', 'normalized', ...
                                            'FontSize', 12, ...
                                            'Position', [ hzsep 1-1/13 0.5 1/13 ], ...
                                            'BackgroundColor', [ 1 1 1 ] );
                                        
cdi.UserData.country_popup = uicontrol ( 'Parent', cdi.UserData.lower_upper_pannel,...
                                         'Style', 'popup', ...
                                         'Units', 'normalized', ...
                                         'String', country_popup, ...
                                         'FontSize', 12, ...
                                         'Position', [ 0.3 1-1/13 0.2 1/13 ], ...
                                         'BackgroundColor', [ 1 1 1 ], ...
                                         'Callback', @countryChangedCallBack );
cdi.UserData.factor1 = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                  'Style', 'text', ...
                                  'String', [ 'F1: ' cdi.UserData.variables.factor1 ], ...
                                  'HorizontalAlignment', 'left', ...
                                  'Units', 'normalized', ...
                                  'FontSize', 12, ...
                                  'Position', [ 0.6 1-1.15/13 0.5 1/13 ], ...
                                  'BackgroundColor', [ 1 1 1 ], ...
                                  'Visible', 'off' );
                                    
% Surface Elevation
cdi.UserData.surface_elevation = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                            'Style', 'text', ...
                                            'String', surface_elevation_string, ...
                                            'HorizontalAlignment', 'left', ...
                                            'Units', 'normalized', ...
                                            'FontSize', 12, ...
                                            'Position', [ hzsep 1-2*1/13 0.5 1/13 ], ...
                                            'BackgroundColor', [ 1 1 1 ] );
cdi.UserData.surface_elevation_value = uicontrol ( 'Parent', cdi.UserData.lower_upper_pannel,...
                                         'Style', 'edit', ...
                                         'Units', 'normalized', ...
                                         'String', '', ...
                                         'FontSize', 12, ...
                                         'Position', [ 0.3 1-1.5*1/13 0.1 1/20 ], ...
                                         'BackgroundColor', [ 1 1 1 ] );
                                     
cdi.UserData.surface_elevation_unit = uicontrol ( 'Parent', cdi.UserData.lower_upper_pannel,...
                                         'Style', 'text', ...
                                         'Units', 'normalized', ...
                                         'String', length_units, ...
                                         'FontSize', 12, ...
                                         'Position', [ 0.41 1-2*1/13 0.05 1/13 ], ...
                                         'BackgroundColor', [ 1 1 1 ] );
cdi.UserData.factor2 = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                  'Style', 'text', ...
                                  'String', [ 'F2: ' cdi.UserData.variables.factor2 ], ...
                                  'HorizontalAlignment', 'left', ...
                                  'Units', 'normalized', ...
                                  'FontSize', 12, ...
                                  'Position', [ 0.6 1-2*1/13 0.5 1/13 ], ...
                                  'BackgroundColor', [ 1 1 1 ], ...
                                  'Visible', 'off' );
% Spud Depth
cdi.UserData.spud_depth = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                            'Style', 'text', ...
                                            'String', spud_depth_string, ...
                                            'HorizontalAlignment', 'left', ...
                                            'Units', 'normalized', ...
                                            'FontSize', 12, ...
                                            'Position', [ hzsep 1-3*1/13 0.5 1/13 ], ...
                                            'BackgroundColor', [ 1 1 1 ] );

cdi.UserData.spud_depth_value = uicontrol ( 'Parent', cdi.UserData.lower_upper_pannel,...
                                         'Style', 'edit', ...
                                         'Units', 'normalized', ...
                                         'String', '', ...
                                         'FontSize', 12, ...
                                         'Position', [ 0.3 1-2.5*1/13 0.1 1/20 ], ...
                                         'BackgroundColor', [ 1 1 1 ] );
                                     
cdi.UserData.spud_depth_unit = uicontrol ( 'Parent', cdi.UserData.lower_upper_pannel,...
                                         'Style', 'text', ...
                                         'Units', 'normalized', ...
                                         'String', length_units, ...
                                         'FontSize', 12, ...
                                         'Position', [ 0.41 1-3*1/13 0.05 1/13 ], ...
                                         'BackgroundColor', [ 1 1 1 ] );
% Measured Total Depth                                        
cdi.UserData.MTD = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                            'Style', 'text', ...
                                            'String', 'Measured Total Depth:', ...
                                            'HorizontalAlignment', 'left', ...
                                            'Units', 'normalized', ...
                                            'FontSize', 12, ...
                                            'Position', [ hzsep 1-4*1/13 0.5 1/13 ], ...
                                            'BackgroundColor', [ 1 1 1 ] );
cdi.UserData.MTD_value = uicontrol ( 'Parent', cdi.UserData.lower_upper_pannel,...
                                         'Style', 'edit', ...
                                         'Units', 'normalized', ...
                                         'String', '', ...
                                         'FontSize', 12, ...
                                         'Position', [ 0.3 1-3.5*1/13 0.1 1/20 ], ...
                                         'BackgroundColor', [ 1 1 1 ] );
                                     
cdi.UserData.MTD_unit = uicontrol ( 'Parent', cdi.UserData.lower_upper_pannel,...
                                         'Style', 'text', ...
                                         'Units', 'normalized', ...
                                         'String', length_units, ...
                                         'FontSize', 12, ...
                                         'Position', [ 0.41 1-4*1/13 0.05 1/13 ], ...
                                         'BackgroundColor', [ 1 1 1 ] );

% Drilled Interval                                        
cdi.UserData.DI = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                            'Style', 'text', ...
                                            'String', 'Drilled Interval:', ...
                                            'HorizontalAlignment', 'left', ...
                                            'Units', 'normalized', ...
                                            'FontSize', 12, ...
                                            'Position', [ hzsep 1-5*1/13 0.5 1/13 ], ...
                                            'BackgroundColor', [ 1 1 1 ] );
                                        
cdi.UserData.DI_value = uicontrol ( 'Parent', cdi.UserData.lower_upper_pannel,...
                                         'Style', 'text', ...
                                         'Units', 'normalized', ...
                                         'String', '' , ...
                                         'FontSize', 12, ...
                                         'Position', [ 0.3 1-4.5*1/13 0.1 1/20 ], ...
                                         'BackgroundColor', [ 1 1 1 ] );
                                     
                                     
cdi.UserData.DI_unit = uicontrol ( 'Parent', cdi.UserData.lower_upper_pannel,...
                                         'Style', 'text', ...
                                         'Units', 'normalized', ...
                                         'String', length_units, ...
                                         'FontSize', 12, ...
                                         'Position', [ 0.41 1-5*1/13 0.05 1/13 ], ...
                                         'BackgroundColor', [ 1 1 1 ] );
cdi.UserData.factor3 = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                  'Style', 'text', ...
                                  'String', [ 'F3: ' cdi.UserData.variables.factor3 ], ...
                                  'HorizontalAlignment', 'left', ...
                                  'Units', 'normalized', ...
                                  'FontSize', 12, ...
                                  'Position', [ 0.6 1-5*1/13 0.5 1/13 ], ...
                                  'BackgroundColor', [ 1 1 1 ], ...
                                  'Visible', 'off');


% Maximum Angle                                        
cdi.UserData.maximum_angle = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                            'Style', 'text', ...
                                            'String', 'Maximum Angle:', ...
                                            'HorizontalAlignment', 'left', ...
                                            'Units', 'normalized', ...
                                            'FontSize', 12, ...
                                            'Position', [ hzsep 1-6*1/13 0.5 1/13 ], ...
                                            'BackgroundColor', [ 1 1 1 ] );
cdi.UserData.maximum_angle_unit = uicontrol ( 'Parent', cdi.UserData.lower_upper_pannel,...
                                         'Style', 'text', ...
                                         'Units', 'normalized', ...
                                         'String', 'deg', ...
                                         'FontSize', 12, ...
                                         'Position', [ 0.41 1-5.85*1/13 0.05 1/13 ], ...
                                         'BackgroundColor', [ 1 1 1 ] );           

cdi.UserData.maximum_angle_popup = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                            'Style', 'popup', ...
                                            'String', onshore_maximum_angle_popup, ...
                                            'HorizontalAlignment', 'left', ...
                                            'Units', 'normalized', ...
                                            'FontSize', 12, ...
                                            'Position', [ 0.3 1-5.75*1/13 0.1 1/13 ], ...
                                            'BackgroundColor', [ 1 1 1 ], ...
                                            'Callback', @maximumAngleChangedCallback ); 
cdi.UserData.factor4 = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                  'Style', 'text', ...
                                  'String', [ 'F4: ' cdi.UserData.variables.factor4 ], ...
                                  'HorizontalAlignment', 'left', ...
                                  'Units', 'normalized', ...
                                  'FontSize', 12, ...
                                  'Position', [ 0.6 1-5.75*1/13 0.5 1/13 ], ...
                                  'BackgroundColor', [ 1 1 1 ],...
                                  'Visible', 'off');
% Horizontal Section
cdi.UserData.lenght_HS = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                            'Style', 'text', ...
                                            'String', 'Length of Horizontal Section:', ...
                                            'HorizontalAlignment', 'left', ...
                                            'Units', 'normalized', ...
                                            'FontSize', 12, ...
                                            'Position', [ hzsep 1-7*1/13 0.5 1/13 ], ...
                                            'BackgroundColor', [ 1 1 1 ] );
cdi.UserData.length_HS_value = uicontrol ( 'Parent', cdi.UserData.lower_upper_pannel,...
                                         'Style', 'edit', ...
                                         'Units', 'normalized', ...
                                         'String', '', ...
                                         'FontSize', 12, ...
                                         'Position', [ 0.3 1-6.5*1/13 0.1 1/20 ], ...
                                         'BackgroundColor', [ 1 1 1 ] );
                                     
cdi.UserData.length_HS_unit = uicontrol ( 'Parent', cdi.UserData.lower_upper_pannel,...
                                         'Style', 'text', ...
                                         'Units', 'normalized', ...
                                         'String', length_units, ...
                                         'FontSize', 12, ...
                                         'Position', [ 0.41 1-6.95*1/13 0.05 1/13 ], ...
                                         'BackgroundColor', [ 1 1 1 ] );
cdi.UserData.factor5 = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                  'Style', 'text', ...
                                  'String', [ 'F5: ' cdi.UserData.variables.factor5 ], ...
                                  'HorizontalAlignment', 'left', ...
                                  'Units', 'normalized', ...
                                  'FontSize', 12, ...
                                  'Position', [ 0.6 1-6.95*1/13 0.5 1/13 ], ...
                                  'BackgroundColor', [ 1 1 1 ],...
                                  'Visible', 'off' );

% Final Bit Size
cdi.UserData.final_bit_size = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                            'Style', 'text', ...
                                            'String', 'Final Bit Size:', ...
                                            'HorizontalAlignment', 'left', ...
                                            'Units', 'normalized', ...
                                            'FontSize', 12, ...
                                            'Position', [ hzsep 1-8*1/13 0.5 1/13 ], ...
                                            'BackgroundColor', [ 1 1 1 ] );
cdi.UserData.bit_size_popup = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                            'Style', 'popup', ...
                                            'String', onshore_bit_size_popup, ...
                                            'HorizontalAlignment', 'left', ...
                                            'Units', 'normalized', ...
                                            'FontSize', 12, ...
                                            'Position', [ 0.3 1-7.75*1/13 0.1 1/13 ], ...
                                            'BackgroundColor', [ 1 1 1 ], ...
                                            'Callback', @bitSizeChangedCallback );              

cdi.UserData.bit_size_unit = uicontrol ( 'Parent', cdi.UserData.lower_upper_pannel,...
                                         'Style', 'text', ...
                                         'Units', 'normalized', ...
                                         'String', 'in', ...
                                         'FontSize', 12, ...
                                         'Position', [ 0.41 1-8*1/13 0.05 1/13 ], ...
                                         'BackgroundColor', [ 1 1 1 ] );
cdi.UserData.factor6 = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                  'Style', 'text', ...
                                  'String', [ 'F6: ' cdi.UserData.variables.factor6 ], ...
                                  'HorizontalAlignment', 'left', ...
                                  'Units', 'normalized', ...
                                  'FontSize', 12, ...
                                  'Position', [ 0.6 1-8*1/13 0.5 1/13 ], ...
                                  'BackgroundColor', [ 1 1 1 ], ...
                                  'Visible', 'off');
% Number of casings
cdi.UserData.number_of_casings = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                            'Style', 'text', ...
                                            'String', 'Number of Casings:', ...
                                            'HorizontalAlignment', 'left', ...
                                            'Units', 'normalized', ...
                                            'FontSize', 12, ...
                                            'Position', [ hzsep 1-9*1/13 0.5 1/13 ], ...
                                            'BackgroundColor', [ 1 1 1 ] );
cdi.UserData.number_of_casings_popup = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                            'Style', 'popup', ...
                                            'String', onshore_number_of_casings_popup, ...
                                            'HorizontalAlignment', 'left', ...
                                            'Units', 'normalized', ...
                                            'FontSize', 12, ...
                                            'Position', [ 0.3 1-8.75*1/13 0.1 1/13 ], ...
                                            'BackgroundColor', [ 1 1 1 ], ...
                                            'Callback', @numberOfCasingsChangedCallback ); 
cdi.UserData.factor7 = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                  'Style', 'text', ...
                                  'String', [ 'F7: ' cdi.UserData.variables.factor7 ], ...
                                  'HorizontalAlignment', 'left', ...
                                  'Units', 'normalized', ...
                                  'FontSize', 12, ...
                                  'Position', [ 0.6 1-8.75*1/13 0.5 1/13 ], ...
                                  'BackgroundColor', [ 1 1 1 ],...
                                  'Visible', 'off');

% Maximum Mud Weight
cdi.UserData.maximum_MW = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                            'Style', 'text', ...
                                            'String', 'Maximum Mud Weight:', ...
                                            'HorizontalAlignment', 'left', ...
                                            'Units', 'normalized', ...
                                            'FontSize', 12, ...
                                            'Position', [ hzsep 1-10/13 0.5 1/13 ], ...
                                            'BackgroundColor', [ 1 1 1 ] );
                                        
cdi.UserData.maximum_MW_value = uicontrol ( 'Parent', cdi.UserData.lower_upper_pannel,...
                                         'Style', 'edit', ...
                                         'Units', 'normalized', ...
                                         'String', '', ...
                                         'FontSize', 12, ...
                                         'Position', [ 0.3 1-9.35*1/13 0.1 1/20 ], ...
                                         'BackgroundColor', [ 1 1 1 ] );
                                     
cdi.UserData.maximum_MW_unit = uicontrol ( 'Parent', cdi.UserData.lower_upper_pannel,...
                                         'Style', 'text', ...
                                         'Units', 'normalized', ...
                                         'String', density_units, ...
                                         'FontSize', 12, ...
                                         'Position', [ 0.41 1-9.85*1/13 0.07 1/13 ], ...
                                         'BackgroundColor', [ 1 1 1 ] );
cdi.UserData.factor8 = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                  'Style', 'text', ...
                                  'String', [ 'F8: ' cdi.UserData.variables.factor8 ], ...
                                  'HorizontalAlignment', 'left', ...
                                  'Units', 'normalized', ...
                                  'FontSize', 12, ...
                                  'Position', [ 0.6 1-9.85*1/13 0.5 1/13 ], ...
                                  'BackgroundColor', [ 1 1 1 ],...
                                  'Visible', 'off');

% High Pressure
cdi.UserData.high_pressure = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                            'Style', 'text', ...
                                            'String', 'High Pressure?:', ...
                                            'HorizontalAlignment', 'left', ...
                                            'Units', 'normalized', ...
                                            'FontSize', 12, ...
                                            'Position', [ hzsep 1-11*1/13 0.5 1/13 ], ...
                                            'BackgroundColor', [ 1 1 1 ] );
cdi.UserData.high_pressure_popup = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                            'Style', 'popup', ...
                                            'String', { 'No', 'Yes' }, ...
                                            'HorizontalAlignment', 'left', ...
                                            'Units', 'normalized', ...
                                            'FontSize', 12, ...
                                            'Position', [ 0.3 1-10.75*1/13 0.1 1/13 ], ...
                                            'BackgroundColor', [ 1 1 1 ], ...
                                            'Callback', @HPChangedCallback );
cdi.UserData.factor9 = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                  'Style', 'text', ...
                                  'String', [ 'F9: ' cdi.UserData.variables.factor9 ], ...
                                  'HorizontalAlignment', 'left', ...
                                  'Units', 'normalized', ...
                                  'FontSize', 12, ...
                                  'Position', [ 0.6 1-10.75*1/13 0.5 1/13 ], ...
                                  'BackgroundColor', [ 1 1 1 ],...
                                  'Visible', 'off');
% Age of oldest Reservoir
cdi.UserData.reservoir_age = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                            'Style', 'text', ...
                                            'String', 'Oldest Reservoir Age:', ...
                                            'HorizontalAlignment', 'left', ...
                                            'Units', 'normalized', ...
                                            'FontSize', 12, ...
                                            'Position', [ hzsep 1-12*1/13 0.5 1/13 ], ...
                                            'BackgroundColor', [ 1 1 1 ] );
cdi.UserData.reservoir_age_popup = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                            'Style', 'popup', ...
                                            'String', cdi.UserData.variables.ReservoirAge_popup, ...
                                            'HorizontalAlignment', 'left', ...
                                            'Units', 'normalized', ...
                                            'FontSize', 12, ...
                                            'Position', [ 0.3 1-11.75*1/13 0.15 1/13 ], ...
                                            'BackgroundColor', [ 1 1 1 ], ...
                                            'Callback', @reservoirAgeChangedCallback ); 
cdi.UserData.factor10 = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                   'Style', 'text', ...
                                   'String', [ 'F10: ' cdi.UserData.variables.factor10 ], ...
                                   'HorizontalAlignment', 'left', ...
                                   'Units', 'normalized', ...
                                   'FontSize', 12, ...
                                   'Position', [ 0.6 1-11.75*1/13 0.5 1/13 ], ...
                                   'BackgroundColor', [ 1 1 1 ], ...
                                   'Visible', 'off' );

  
% Batch or Campaign Drilled
cdi.UserData.batch_or_campaign = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                            'Style', 'text', ...
                                            'String', 'Batch Drilling:', ...
                                            'HorizontalAlignment', 'left', ...
                                            'Units', 'normalized', ...
                                            'FontSize', 12, ...
                                            'Position', [ hzsep 1-13/13 0.5 1/13 ], ...
                                            'BackgroundColor', [ 1 1 1 ] ); 
cdi.UserData.batch_or_campign_popup = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                            'Style', 'popup', ...
                                            'String', { 'No', 'Yes' }, ...
                                            'HorizontalAlignment', 'left', ...
                                            'Units', 'normalized', ...
                                            'FontSize', 12, ...
                                            'Position', [ 0.3 1-12.75*1/13 0.1 1/13 ], ...
                                            'BackgroundColor', [ 1 1 1 ], ...
                                            'Callback', @batchOrCampaignChanged );
cdi.UserData.factor11 = uicontrol( 'Parent', cdi.UserData.lower_upper_pannel, ...
                                  'Style', 'text', ...
                                  'String', [ 'F11: ' cdi.UserData.variables.factor11 ], ...
                                  'HorizontalAlignment', 'left', ...
                                  'Units', 'normalized', ...
                                  'FontSize', 12, ...
                                  'Position', [ 0.6 1-12.75*1/13 0.5 1/13 ], ...
                                  'BackgroundColor', [ 1 1 1 ], ...
                                  'Visible', 'off');


%% Getting the underlying Java editbox for input validation

cdi.UserData.jsurface_elevation_value = findjobj( cdi.UserData.surface_elevation_value );   % Get Java properties
set( cdi.UserData.jsurface_elevation_value, 'KeyPressedCallback', @validateNumericData );   % Set validation function
set( cdi.UserData.jsurface_elevation_value, 'FocusLostCallback', { @surfaceElevationUpdate } ); % Set FocusLost

cdi.UserData.jspud_depth_value = findjobj( cdi.UserData.spud_depth_value );
set( cdi.UserData.jspud_depth_value, 'KeyPressedCallback', @validateNumericData );
set( cdi.UserData.jspud_depth_value, 'FocusLostCallback', { @spudDepthUpdate } ); % Set FocusLost

cdi.UserData.jMTD_value = findjobj( cdi.UserData.MTD_value );
set( cdi.UserData.jMTD_value, 'KeyPressedCallback', @validateNumericData );
set( cdi.UserData.jMTD_value, 'FocusLostCallback', { @MTDUpdate } ); % Set FocusLost

cdi.UserData.jlength_HS_value = findjobj( cdi.UserData.length_HS_value );
set( cdi.UserData.jlength_HS_value, 'KeyPressedCallback', @validateNumericData );
set( cdi.UserData.jlength_HS_value, 'FocusLostCallback', { @HSUpdate } ); % Set FocusLost

cdi.UserData.jmaximum_MW_value = findjobj( cdi.UserData.maximum_MW_value );
set( cdi.UserData.jmaximum_MW_value, 'KeyPressedCallback', @validateNumericData );
set( cdi.UserData.jmaximum_MW_value, 'FocusLostCallback', { @MWUpdate } ); % Set FocusLost

                                        
%% Callback functions
    function welltypeselection( ~, callbackdata )
        if ( strcmp( callbackdata.NewValue.String, 'Offshore Well' ) )
            welltype = 'Offshore';
            country_popup = sort( cdi.UserData.variables.CountryOffshoreList );
            cdi.UserData.variables.Offshore = 1;
            cdi.UserData.variables.Onshore = 0;
            % Populate pop-ups and update variables' values
            % Maximum Angle
            set( cdi.UserData.maximum_angle_popup, 'String', offshore_maximum_angle_popup );
            cdi.UserData.variables.Angle = get( cdi.UserData.maximum_angle_popup, 'Value' );
            % Calculate factor and update on the screen
            cdi.UserData.variables.factor4 = maximumAngleFactor( cdi.UserData.variables.Angle, welltype, 'CDI' );
            updateFactorOnScreen( 4, cdi.UserData.variables.factor4 );
            % Bit Size
            set ( cdi.UserData.bit_size_popup, 'String', offshore_bit_size_popup );
            cdi.UserData.variables.BitSize = get( cdi.UserData.bit_size_popup, 'Value' );
            % Calculate factor and update on the screen
            cdi.UserData.variables.factor6 = FinalBitSizeFactor( cdi.UserData.variables.BitSize, welltype, 'CDI' );
            updateFactorOnScreen( 6, cdi.UserData.variables.factor6 );
            % Number of Casings
            set( cdi.UserData.number_of_casings_popup, 'String', offshore_number_of_casings_popup );
            cdi.UserData.variables.NumberOfCasings = get( cdi.UserData.number_of_casings_popup, 'Value' );
            % Calculate factor and update on the screen
            cdi.UserData.variables.factor7 = NumberofCasingFactor( cdi.UserData.variables.NumberOfCasings, welltype, 'CDI' );
            updateFactorOnScreen( 7, cdi.UserData.variables.factor7 );
            %Batch or Campaign Drilling
            
            % Update country list
            set( cdi.UserData.country_popup, 'String', country_popup );
            cdi.UserData.variables.Country = country_popup{ get( cdi.UserData.country_popup, 'Value' ) };
            % Calculate factor and update on the screen
            cdi.UserData.variables.factor1 = countryFactor( cdi.UserData.variables.Country, welltype, 'CDI' );
            updateFactorOnScreen( 1, cdi.UserData.variables.factor1 );
            % Update labels
            updateLabels();
        else
            cdi.UserData.variables.Offshore = 0;
            cdi.UserData.variables.Onshore = 1;
            welltype = 'Onshore';
            country_popup = sort( cdi.UserData.variables.CountryLandList );
            % Populate pop-ups and update variables' values
            % Maximum Angle
            set( cdi.UserData.maximum_angle_popup, 'String', onshore_maximum_angle_popup );
            cdi.UserData.variables.Angle = get( cdi.UserData.maximum_angle_popup, 'Value' ) - 1;
            % Calculate factor and update on the screen
            cdi.UserData.variables.factor4 = maximumAngleFactor( cdi.UserData.variables.Angle, welltype, 'CDI' );
            updateFactorOnScreen( 4, cdi.UserData.variables.factor4 );
            % Bit Size
            set ( cdi.UserData.bit_size_popup, 'String', onshore_bit_size_popup );
            cdi.UserData.variables.BitSize = get( cdi.UserData.bit_size_popup, 'Value' );
            % Calculate factor and update on the screen
            cdi.UserData.variables.factor6 = FinalBitSizeFactor( cdi.UserData.variables.BitSize, welltype, 'CDI' );
            updateFactorOnScreen( 6, cdi.UserData.variables.factor6 );
            % Number of Casings
            set( cdi.UserData.number_of_casings_popup, 'String', onshore_number_of_casings_popup );
            cdi.UserData.variables.NumberOfCasings = get( cdi.UserData.number_of_casings_popup, 'Value' );
             % Calculate factor and update on the screen
            cdi.UserData.variables.factor7 = NumberofCasingFactor( cdi.UserData.variables.NumberOfCasings, welltype, 'CDI' );
            updateFactorOnScreen( 7, cdi.UserData.variables.factor7 );
            % Reservoir Age
            % Calculate factor and update on the screen
            cdi.UserData.variables.ReservoirAge = get( cdi.UserData.reservoir_age_popup, 'Value' );
            cdi.UserData.variables.factor10 = ReservoirAgeFactor( cdi.UserData.variables.ReservoirAge, welltype, 'CDI' );
            updateFactorOnScreen( 10, cdi.UserData.variables.factor10 );   
            % Batch or Campaign Drilling
            % Update country list
            set( cdi.UserData.country_popup, 'String', country_popup );
            cdi.UserData.variables.Country = country_popup{ get( cdi.UserData.country_popup, 'Value' ) };
            % Calculate factor and update on the screen
            cdi.UserData.variables.factor1 = countryFactor( cdi.UserData.variables.Country, welltype, 'CDI' );
            updateFactorOnScreen( 1, cdi.UserData.variables.factor1 );
            updateLabels();
        end        
    end

    function lengthselection( source, ~ )
        cdi.UserData.variables.LengthUnits = source.String{ source.Value };
        updateUnitsLabel();
        if ( cdi.UserData.variables.LengthUnits ~= length_units )
            % Surface Elevation 
            if ( ~isnan( str2double( cdi.UserData.jsurface_elevation_value.getText ) ) )
                value = changeLengthUnits( str2double( cdi.UserData.jsurface_elevation_value.getText ), ...
                length_units, cdi.UserData.variables.LengthUnits );
                set( cdi.UserData.surface_elevation_value, 'String', num2str( value ) );
                cdi.UserData.variables.SurfaceElevation = str2double( get( cdi.UserData.surface_elevation_value, 'String' ) );
            end
            % Spud Depth
            if ( ~isnan( str2double( cdi.UserData.jspud_depth_value.getText ) ) )
                value = changeLengthUnits( str2double( cdi.UserData.jspud_depth_value.getText ), ...
                    length_units, cdi.UserData.variables.LengthUnits );
                set( cdi.UserData.spud_depth_value, 'String', num2str( value ) );
                cdi.UserData.variables.SpudDepth = str2double( get( cdi.UserData.spud_depth_value, 'String' ) );
            end
            % Measured Total Depth
            if ( ~isnan( str2double( cdi.UserData.jMTD_value.getText ) ) )
                value = changeLengthUnits( str2double( cdi.UserData.jMTD_value.getText ), ...
                    length_units, cdi.UserData.variables.LengthUnits );
                set( cdi.UserData.MTD_value, 'String', num2str( value ) );
                cdi.UserData.variables.MTD = str2double( get( cdi.UserData.MTD_value, 'String' ) );
            end
            % Drilled Interval
            if ( ~isnan( str2double( cdi.UserData.DI_value.String ) ) )
                value = changeLengthUnits( str2double( cdi.UserData.DI_value.String ), ...
                    length_units, cdi.UserData.variables.LengthUnits );
                set( cdi.UserData.DI_value, 'String', num2str( value ) );
                cdi.UserData.variables.DrilledInterval = str2double( get( cdi.UserData.DI_value, 'String' ) );
            end
            % Horizontal Section
            if ( ~isnan( str2double( cdi.UserData.jlength_HS_value.getText ) ) )
                value = changeLengthUnits( str2double( cdi.UserData.jlength_HS_value.getText ), ...
                    length_units, cdi.UserData.variables.LengthUnits );
                set( cdi.UserData.length_HS_value, 'String', num2str( value ) );
                cdi.UserData.variables.HorSection = str2double( get( cdi.UserData.length_HS_value, 'String' ) );
            end
           length_units = cdi.UserData.variables.LengthUnits;
        end
    end

    function densityselection( source, ~ )
        cdi.UserData.variables.DensityUnits = source.String{ source.Value };
        updateUnitsLabel();
        if ~strcmp( cdi.UserData.variables.DensityUnits, density_units )
            % Maximum Mud Weight
            if ( ~isnan( str2double( cdi.UserData.jmaximum_MW_value.getText ) ) )
                value = changeDensityUnits( str2double( cdi.UserData.jmaximum_MW_value.getText ), ...
                    density_units, cdi.UserData.variables.DensityUnits );
                set( cdi.UserData.maximum_MW_value, 'String', num2str( value ) );
                cdi.UserData.variables.MudWeight = str2double( get( cdi.UserData.maximum_MW_value, 'String' ) );
           end
           density_units = cdi.UserData.variables.DensityUnits;           
        end

    end

    function countryChangedCallBack( source, ~ )
        cdi.UserData.variables.Country = source.String{ source.Value };
        cdi.UserData.variables.factor1 = countryFactor( cdi.UserData.variables.Country, welltype, 'CDI' );
        updateFactorOnScreen( 1, cdi.UserData.variables.factor1 );
    end

    % Data validation for edit boxes
    function validateNumericData( source, eventData )
        keyChar = eventData.getKeyChar;     
        if ~alldigits( keyChar ) && isprintable( keyChar )
            fixedText = strrep( char( source.getText ), keyChar, '' );
            source.setText( fixedText );
            source.setCursor( fixedText.length );
        end        
    end
    
    function surfaceElevationUpdate( source, ~ )
        if ~isempty( source.getText ) && ( source.getText ~= ' ' )
            cdi.UserData.variables.SurfaceElevation = str2double( source.getText );
            if ( strcmp( welltype, 'Offshore' ) )
                cdi.UserData.variables.factor2 = WDFactor( cdi.UserData.variables.SurfaceElevation, 'CDI' );
                updateFactorOnScreen( 2, cdi.UserData.variables.factor2 );
            end
            % Update drilled interval (if needed)
            updateDrilledInterval();
        end
    end

    function spudDepthUpdate( source, ~ )
        if ~isempty( source.getText ) && ( source.getText ~= ' ' )
            cdi.UserData.variables.SpudDepth = str2double( source.getText );         
            % Update drilled interval (if needed)
            updateDrilledInterval();
        end
    end

    function MTDUpdate( source, ~ )
        if ~isempty( source.getText ) && ( source.getText ~= ' ' )
            cdi.UserData.variables.MTD = str2double( source.getText );
        end
        % Update drilled interval (if needed )
        updateDrilledInterval();
    end

    function HSUpdate( source, ~ )
        if ~isempty( source.getText ) && ( source.getText ~= ' ' )
            cdi.UserData.variables.HorSection = str2double( source.getText );
            if ( cdi.UserData.variables.HorSection == 0 )
                cdi.UserData.variables.HorSection = 1;
            elseif ( cdi.UserData.variables.HorSection < 500 )
                cdi.UserData.variables.HorSection = 2;
            elseif ( cdi.UserData.variables.HorSection < 1000 )
                cdi.UserData.variables.HorSection = 3;
            elseif ( cdi.UserData.variables.HorSection < 2000 )
                cdi.UserData.variables.HorSection = 4;
            else
                cdi.UserData.variables.HorSection = 5;
            end
                
            cdi.UserData.variables.factor5 = HSFactor( cdi.UserData.variables.HorSection, 'CDI' );
            updateFactorOnScreen( 5, cdi.UserData.variables.factor5 );
        end
    end

    function MWUpdate( source, ~ )
        if ~isempty( source.getText ) && ( source.getText ~= ' ' )
            cdi.UserData.variables.MudWeight = str2double( source.getText );
            cdi.UserData.variables.factor8 = MaximumMWFactor( cdi.UserData.variables.MudWeight, welltype, 'CDI' );
            updateFactorOnScreen( 8, cdi.UserData.variables.factor8 );
        end        
    end

    function maximumAngleChangedCallback( source, ~ )
        if (  cdi.UserData.variables.Offshore ) 
            cdi.UserData.variables.Angle =  source.Value;
            cdi.UserData.variables.factor4 = maximumAngleFactor( cdi.UserData.variables.Angle, welltype, 'CDI' );
            updateFactorOnScreen( 4, cdi.UserData.variables.factor4 );
        else
            cdi.UserData.variables.Angle = source.Value - 1;
            cdi.UserData.variables.factor4 = maximumAngleFactor( cdi.UserData.variables.Angle, welltype, 'CDI' );
            updateFactorOnScreen( 4, cdi.UserData.variables.factor4 );
        end        
    end

    function bitSizeChangedCallback( source, ~ )
        cdi.UserData.variables.BitSize = source.Value;
        cdi.UserData.variables.factor6 = FinalBitSizeFactor( cdi.UserData.variables.BitSize, welltype, 'CDI' );
        updateFactorOnScreen( 6, cdi.UserData.variables.factor6 );
    end

    function numberOfCasingsChangedCallback( source, ~ )
        cdi.UserData.variables.NumberOfCasings = source.Value;
        cdi.UserData.variables.factor7 = NumberofCasingFactor( cdi.UserData.variables.NumberOfCasings, welltype, 'CDI' );
        updateFactorOnScreen( 7, cdi.UserData.variables.factor7 );
    end

    function HPChangedCallback( source, ~ )
        cdi.UserData.variables.HPWell = source.String{ source.Value };
        switch ( cdi.UserData.variables.HPWell )
            case 'No'
                cdi.UserData.variables.HPWell = 0;
            case 'Yes'
                cdi.UserData.variables.HPWell = 1;
        end
        cdi.UserData.variables.factor9 = HPFactor( cdi.UserData.variables.HPWell, welltype, 'CDI' );
        updateFactorOnScreen( 9, cdi.UserData.variables.factor9 );
    end

    function reservoirAgeChangedCallback( source, ~ )
        cdi.UserData.variables.ReservoirAge = source.String{ source.Value };
        cdi.UserData.variables.factor10 = ReservoirAgeFactor( cdi.UserData.variables.ReservoirAge, welltype, 'CDI' );
        updateFactorOnScreen( 10, cdi.UserData.variables.factor10 );
    end

    function batchOrCampaignChanged( source, ~ )
        cdi.UserData.variables.BatchOrCampaign = source.String { source.Value };
        switch ( cdi.UserData.variables.BatchOrCampaign )
            case 'No'
                cdi.UserData.variables.BatchOrCampaign = 0;
            case 'Yes'
                cdi.UserData.variables.BatchOrCampaign = 1;
        end
        cdi.UserData.variables.factor11 = BatchFactor( cdi.UserData.variables.BatchOrCampaign, welltype, 'CDI' );
        updateFactorOnScreen( 11, cdi.UserData.variables.factor11 );
    end

%% Auxiliary functions
% Function to update strings in case welltype changes
    function updateLabels()
       if ( cdi.UserData.variables.Offshore )
           surface_elevation_string = 'Water Depth Elevation:';
           spud_depth_string = 'Spud Depth @ Mud line:';
       else
           surface_elevation_string = 'Rotary Table Height:';
           spud_depth_string = 'Spud Depth @ Cellar Bottom:';
       end
       set( cdi.UserData.surface_elevation, 'String', surface_elevation_string );
       set( cdi.UserData.spud_depth, 'String', spud_depth_string );
    end

    % Check whether a string only contains digits
    function flag = alldigits( str )
        flag = ( ~isnan( str2double( str ) ) || str == '.' );
    end

    % Check whether a character is printable
    function flag = isprintable( keyChar )
        keyVal = double( keyChar );
        flag = ~isempty( keyVal ) && keyVal > 31 && keyVal < 128;
    end

    % Function to update Drilled Interval (called by surfaceElevationUpdate and spudDepthUpdate)
    function updateDrilledInterval()
        
        if ( ~isempty( cdi.UserData.jsurface_elevation_value.getText ) && ...
                ~isempty( cdi.UserData.jspud_depth_value.getText ) && ...
                ~isempty( cdi.UserData.jMTD_value.getText ) )
            cdi.UserData.variables.DrilledInterval = str2double( cdi.UserData.jMTD_value.getText ) - ...
                str2double( cdi.UserData.jspud_depth_value.getText );
            
            % Display new value
            if ( isnan( cdi.UserData.variables.DrilledInterval ) )
                set( cdi.UserData.DI_value, 'String', ' ' );
            else
                set( cdi.UserData.DI_value, 'String', num2str( cdi.UserData.variables.DrilledInterval ) );
                cdi.UserData.variables.factor3 = DIFactor( cdi.UserData.variables.DrilledInterval, welltype, 'CDI' );
                updateFactorOnScreen( 3, cdi.UserData.variables.factor3 );
            end
        end
    end
    
    % This function updates labels depending on the unit selected
    function updateUnitsLabel()
        set( cdi.UserData.surface_elevation_unit, 'String', cdi.UserData.variables.LengthUnits );
        set( cdi.UserData.spud_depth_unit, 'String', cdi.UserData.variables.LengthUnits );
        set( cdi.UserData.MTD_unit, 'String', cdi.UserData.variables.LengthUnits );
        set( cdi.UserData.DI_unit, 'String', cdi.UserData.variables.LengthUnits );
        set( cdi.UserData.length_HS_unit, 'String', cdi.UserData.variables.LengthUnits );
        set( cdi.UserData.maximum_MW_unit, 'String', cdi.UserData.variables.DensityUnits );
    end 

    function updateFactorOnScreen( factorNum, value )
        % Updates the factor on the screen given the number of the factor
        % Get the handle to the panel that holds the value dynamically
        textBox = eval( sprintf( 'cdi.UserData.factor%d', factorNum ) );
        % Set String property
        set( textBox, 'String', sprintf( 'F%d: %.3f', factorNum, value ) );
        % Make it visible
        set( textBox, 'Visible', 'on' );
    end

end